# Generated by Django 5.0.6 on 2024-07-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_code', models.CharField(max_length=4)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
